export var Global ={
  urlCarnet:   'https://0a6yjaj11b.execute-api.us-east-1.amazonaws.com/dev/carnet',
  urlCita:     'https://jtq2qqbabf.execute-api.us-east-1.amazonaws.com/dev/cita',
  urlEnfermed: 'https://s4pu89w0p5.execute-api.us-east-1.amazonaws.com/dev/enfermedad',
  urlMedico:   'https://6q4x7np717.execute-api.us-east-1.amazonaws.com/dev/medico',
  urlPaciente: 'https://uyfbxbdsr7.execute-api.us-east-1.amazonaws.com/dev/paciente',
  urlPerfil:   'https://j2fgtlvwyh.execute-api.us-east-1.amazonaws.com/dev/perfil',
  urlSignos:   'https://qligm8qqt7.execute-api.us-east-1.amazonaws.com/dev/signos',
  urlSucursal: 'https://c1ta08mzt6.execute-api.us-east-1.amazonaws.com/dev/sucursal',
  urlUsuario:  'https://pwik18v3ai.execute-api.us-east-1.amazonaws.com/dev/usuario',
  
  AGREGAR:'Agregar',
  ACTUALIZAR:'Actualizar',
  ELIMINAR:'Eliminar',
  GUARDAR:'Guardar',
  CANCELAR:'Cancelar',
  AGENDAR: 'Agendar',
  ALTA: 'Alta',
  OK:200,
  MEDICO:'MEDICO',
  ENFERMERA:'ENFERMERA',
  ADMINISTRADOR:'ADMINISTRADOR',
  REPECION:'RECEPCION',
  SUCCESS:'SUCCESS',
  ENTER:13,
  REFRESH_CITA: 60*1000, // cada minuto va ir a consultar si hay nuevas citas
  TIMER_OFF:2500,
  UNO:1,
  MENOSUNO:-1,
  NOMBRE:'nombre',
  APELLIDO:'apellido',
  TELEFONO:'telefono',
  TAB_USUARIO:'usuario',
  TAB_PACIENTE:'paciente',
  TAB_CARNET:'carnet',
  SI:'Si',
  OK_TEXT:'Ok',
  NO:'No'
}