export var Global ={
  urlCarnet:   'https://95fxm0pf8l.execute-api.us-east-1.amazonaws.com/dev/carnet',
  urlCita:     'https://gjxtfu9ve2.execute-api.us-east-1.amazonaws.com/dev/cita',
  urlDisponib: 'https://uxifak5tof.execute-api.us-east-1.amazonaws.com/dev/disponibilidad',
  urlEnfermed: 'https://ekapc7eimk.execute-api.us-east-1.amazonaws.com/dev/enfermedad',
  urlMedicamt: 'https://qrrlv0txqi.execute-api.us-east-1.amazonaws.com/dev/medicamento',
  urlMedico:   'https://s1ic99wjca.execute-api.us-east-1.amazonaws.com/dev/medico',
  urlPaciente: 'https://eg3c501ond.execute-api.us-east-1.amazonaws.com/dev/paciente',
  urlPerfil:   'https://s43bbtyule.execute-api.us-east-1.amazonaws.com/dev/perfil',
  urlPreResAF: 'https://smyllmdu93.execute-api.us-east-1.amazonaws.com/dev/pregresaf',
  urlPregunta: 'https://hqapo3yili.execute-api.us-east-1.amazonaws.com/dev/preguntas',
  urlProducto: 'https://vtzmpzap93.execute-api.us-east-1.amazonaws.com/dev/producto',
  urlSignos:   'https://u02vi9jos6.execute-api.us-east-1.amazonaws.com/dev/signos',
  urlSucursal: 'https://s0keqy0oqb.execute-api.us-east-1.amazonaws.com/dev/sucursal',
  urlUsuario:  'https://bzlnlb9ptd.execute-api.us-east-1.amazonaws.com/dev/usuario',
  urlVentas:   'https://e7lvodtqha.execute-api.us-east-1.amazonaws.com/dev/ventas',
  AGREGAR:'Agregar',
  ACTUALIZAR:'Actualizar',
  ELIMINAR:'Eliminar',
  GUARDAR:'Guardar',
  CANCELAR:'Cancelar',
  AGENDAR: 'Agendar',
  ALTA: 'Alta',
  REGISTRAR:'Registrar',
  OK:200,
  MEDICO:'MEDICO',
  ENFERMERA:'ENFERMERA',
  ADMINISTRADOR:'ADMINISTRADOR',
  REPECION:'RECEPCION',
  SUCCESS:'SUCCESS',
  ENTER:13,
  REFRESH_CITA: 60*1000, // cada minuto va ir a consultar si hay nuevas citas
  TIMER_OFF:2500,
  UNO:1,
  MENOSUNO:-1,
  NOMBRE:'nombre',
  APELLIDO:'apellido',
  TELEFONO:'telefono',
  TAB_USUARIO:'usuario',
  TAB_PACIENTE:'paciente',
  TAB_CARNET:'carnet',
  TAB_CITAS:'citas',
  TAB_ENFERMERIA:'enfermeria',
  TAB_DISPO:'dispo',
  SI:'Si',
  OK_TEXT:'Ok',
  NO:'No',
  COD_MX:'+52',
  DURACION_E1:5,
  DURACION_E2:5,
  DURACION_E3:5,
  DURACION_E4:5,
  FIELD_OK:"form-control border-success",
  FIELD_REQUIRED:"form-control border-danger",
  VERSION:'0.1.1',
  EFECTIVO:'efectivo',
  TARJETA:'tarjeta',
  TRANSFERENCIA:'transferencia',
  CHEQUE:'cheque',
  EMPTY:0,
  LONG_TICKET:6
}